version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.1
    steps:
      - checkout
      - ruby/install-deps
      # Store bundle cache
      #- node/install-packages:
      #    pkg-manager: yarn
      #    cache-key: "yarn.lock"
  test:
    parallelism: 3
    docker:
      - image: circleci/ruby:3.0.1
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci-ruby
          POSTGRES_DB: rails_api_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      #- node/install-packages:
      #    pkg-manager: yarn
      #    cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
